name: sv-style

on: [push]

jobs:
  sv-style:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, macos-latest, windows-latest]
        os: [windows-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build
        run: |
          git clone https://github.com/TerosTechnology/svStyle-SystemVerilog-Formatter.git
          cd svStyle-SystemVerilog-Formatter
          make
      - run: cd svStyle-SystemVerilog-Formatter && ls
      - run: cd svStyle-SystemVerilog-Formatter && cd bin && ls
      - run: cd svStyle-SystemVerilog-Formatter && cd bin && cd release && && 
      - run: 'dir $( $GITHUB_WORKSPACE )'
      - uses: actions/upload-artifact@v2
        with:
          name: svStyle-${{ matrix.os }}
          path: svStyle-SystemVerilog-Formatter/bin/release/svStyle

          